#!/usr/bin/env python3

import random

## characters
upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
lower = "abcdefghijklmnopqrstuvwxyz"
numbers = "0123456789"
special_characters = "[]{}()*;_-/!&%?."

chars = upper + lower + numbers + special_characters

length = input("\nEnter password length (Min. 14 - Max. 78 characters): ")

if int(length) >= 14 and int(length) <= 78:
    password = "".join(random.sample(chars,int(length)))
    print("\nYour password is:",password)

elif int(length) > 78:
    print("\nInvalid input! The password length should be 14 to 78 characters.")

else: 
    print("\nInvalid input!")
