#!/usr/bin/env python3

import random

## characters
upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
lower = "abcdefghijklmnopqrstuvwxyz"
numbers = "0123456789"
special_characters = "[]{}()*;_-/!&%?."

chars = upper + lower + numbers + special_characters

length = input("\nEnter password length (Minimum 14 characters): ")

if int(length) >= 14:
    password = "".join(random.sample(chars,int(length)))
    print("\nYour password is:",password)
else:
    print("\nInvalid input!")
